version: 2

models:
  - name: restaurant_name
    description: "Table containing names of restaurants"
    columns:
      - name: restaurant_name
        description: "The name of the restaurant"
        tests: []  # No tests applied to this column
